version: '3'
services:
  web1:
    build:
      context: ./server
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./server/app/index.js:/server/app/index.js
      - ./server/app/views:/server/app/views
      - ./server/app/public:/server/app/public
      - ./server/app/models:/server/app/models

  web2:
    build:
      context: ./server
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./server/app/index.js:/server/app/index.js
      - ./server/app/views:/server/app/views
      - ./server/app/public:/server/app/public
      - ./server/app/models:/server/app/models

  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    working_dir: "/docker-entrypoint-initdb.d"
    volumes:
      - ./mariadb/:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    restart: 
        "always"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx_cache:/var/cache/nginx
    depends_on:
      - web1
      - web2
      - mariadb

  locust:
    build:
      context: ./locust_nginx
    container_name: "locust"
    working_dir: "/usr/src/app"
    ports:
      - "8089:8089"
    volumes:
      - ./locust_nginx:/usr/src/app
    depends_on:
      - web1
      - web2
      - mariadb
      - nginx