version: '3'
services:
  web1:
    build: .
    environment:
      - PORT=3000
    ports:
      - "3000:3000"

  web2:
    build: .
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
